#!/bin/bash

source ./app/config/env
echo "SNN Feature Generator Util (v $VERSION)"
echo ""

declare -a commands=(
  "build" "Build the snn-feature-generator container"
  "mrun"  "Run program on host machine"
  "crun" "Run the container"
  "setup" "Setup the environment"
)

help_print () {
    echo "Usage: snn-feature-generator <command>"
    echo ""
    echo "commands:"

    arraylength=${#commands[@]}
    for (( i = 0; i < ${arraylength}; i += 2 ));
    do
        echo -e "\t" ${commands[$i]} "\t\t- " ${commands[$i+1]}
    done
}

build_container () {
    docker build -t snn-feature-generator:$VERSION -f Dockerfile .
}

run_on_machine () {
    source /opt/anaconda/bin/activate
    conda activate ./cenv
    cd $APP_DIR/src
    python app.py
    cd $SFG_HOME
}

run_container () {
    docker run snn-feature-generator:$VERSION
}

setup () {
    source /opt/anaconda/bin/activate
    conda create -p ./cenv
    conda activate cenv/
    conda install -c conda-forge --file $CONFIG_DIR/conda.req.list
    pip install -r $CONFIG_DIR/pip.req.list --no-cache-dir
}

op=$1

if [ $op = "build" ]
then
    build_container
elif [ $op = "mrun" ]
then
    run_on_machine
elif [ $op = "crun" ]
then
    run_container
elif [ $op = "setup" ]
then
    setup
else 
    help_print
fi
